language: python
python:
- "2.7"
addons:
apt_packages:
- make
- gcc
- libpython2.7-dev
- unzip
before_script:
- "git clone http://repo.or.cz/tinycc.git tinycc && cd tinycc && git checkout d5e22108a0dc48899e44a158f91d5b3215eb7fe6 && ./configure --disable-static && make && sudo make install && sudo ldconfig && cd ..;"
- "hg clone https://code.google.com/p/elfesteem/ elfesteem && cd elfesteem && python setup.py install && cd ..;"
- "mkdir z3 && cd z3 && wget -O z3.zip 'http://download-codeplex.sec.s-msft.com/Download/SourceControlFileDownload.ashx?ProjectName=z3&changeSetId=cee7dd39444c9060186df79c2a2c7f8845de415b' && unzip -q z3.zip && rm z3.zip && python scripts/mk_make.py && cd build && make -j 32 && sudo make install && cd ../.."
- "pip install pyparsing"
- "python setup.py install"
script: "cd test && python test_all.py -m"
